### ISSUE TITLE
Bug after performing npm start

### ISSUE THREAD

**Issue by connectrv** [AkashRajpurohit/corona-updates-telegram-bot#1]
**Describe the bug**
 code: 401,
  response: { error_code: 401, description: 'Bot Token is required' },
  description: 'Bot Token is required',
  parameters: {},
  on: {}

**Expected behaviour**

**Screenshots**
![a2](https://user-images.githubusercontent.com/20228645/77450606-830b1200-6e19-11ea-8ce9-606ef4cc494d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by AkashRajpurohit** [comment]
Kindly follow the steps mentioned in the Readme.
Follow step 3 which is adding the bot token and other environment variables.

Thank you.

**Comment by connectrv** [comment]
> Kindly follow the steps mentioned in the Readme.
> Follow step 3 which is adding the bot token and other environment variables.
> I did all the steps and added the bot token as well as other items.

![git](https://user-images.githubusercontent.com/20228645/77574059-9096c980-6ef7-11ea-9c10-4cd6985c6d33.PNG)

> Thank you.

**Comment by AkashRajpurohit** [comment]
What issue are you facing again after updating the environment files?
